sudo: false
cache: bundler
language: ruby

# Ensure we don't build for *every* commit (doesn't apply to PR builds)
branches:
  only:
  - master

addons:
  apt:
    packages:
      - ffmpeg

script:
  - cp config/application.yml.sample config/application.yml
  - bundle exec rackup -p 3000 2>&1 &
  - bundle exec rspec --format documentation
